### ISSUE TITLE
No availbale option after browsing the zip

### ISSUE THREAD

**Issue by marjhonie-siasol** [dracula/netbeans#15]
after browsing the zip file from my download path its not showing the all and the fonts of darcula zip file. idk why but yeah it doesnt work for me.

**Comment by jasontdev** [comment]
Please use [dracula-theme-for-netbeans-v0.1.1.zip](https://github.com/dracula/netbeans/files/6574779/dracula-theme-for-netbeans-v0.1.1.zip).
