### ISSUE TITLE
Move to official Dracula organization

### ISSUE THREAD

**Issue by zenorocha** [dracula/netbeans#2]
Hello @jasontdev !

I'm the creator of Dracula color scheme. We were looking for Netbeans themes created by the community and @jpitchardu found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by jasontdev** [comment]
Hello @zenorocha 

I'm happy for the theme to be more visible and be more useful to more people. If I just add support for some more languages then I think it will be ready to move to the official organisation. Issue #3 covers this task.

**Comment by jasontdev** [comment]
Oh and, thank you very much, @zenorocha for Dracula :D

**Comment by zenorocha** [comment]
Sounds good! Let me know when you're ready :)

**Comment by zenorocha** [comment]
Sorry for the delay here, I just sent you an invite to join the org. Once you accept it, you can transfer the repo and I'll handle the site updates.

**Comment by jasontdev** [comment]
All good. Happy to move the repo to the org. Didn't see an invite though?

edit: don't mind me, was looking for an invite on the repo not the org :S

**Comment by jasontdev** [comment]
Transfer to the dracula org now complete.

**Comment by zenorocha** [comment]
It's now live! https://draculatheme.com/netbeans 🎉 🎉 🎉 

Thanks @jasontdev!
