### ISSUE TITLE
Unable to activate theme, no option available to import

### ISSUE THREAD

**Issue by pabloherrero1986** [dracula/netbeans#4]
Downloading the "netbeans-master.zip" and following the steps of the web https://draculatheme.com/netbeans on NetBeans 12.0 seems not to work:

1. Start Netbeans
2. Navigate to theme import dialog: Tools > Options > Fonts & Colors > Import..
3. Click Browse... and select the .zip _[the "netbeans-master.zip" file]_ file downloaded from the release page and then click Ok
4. Ensure All option is checked and then click Ok

The result is this. No option available, even if it is accepted and the theme is restarted, it is not activated:

![image](https://user-images.githubusercontent.com/57707569/106174397-49bbd500-6195-11eb-8688-c961ce4d0309.png)

Could you solve it or tell me what am I doing wrong? Thanks!!!

**Comment by digz6666** [comment]
You should download the dracula-theme-for-netbeans-v0.1.0.zip, not the zipped source code directly from git:
![zip](https://user-images.githubusercontent.com/1736110/106226126-7c131400-6221-11eb-8324-937dcee60881.PNG)

And it will show following import options:
![import1](https://user-images.githubusercontent.com/1736110/106226141-80d7c800-6221-11eb-97b8-ae3c9ea59a3c.PNG)

**Comment by pabloherrero1986** [comment]
> You should download the dracula-theme-for-netbeans-v0.1.0.zip, not the zipped source code directly from git:
> ![zip](https://user-images.githubusercontent.com/1736110/106226126-7c131400-6221-11eb-8324-937dcee60881.PNG)
> 
> And it will show following import options:
> ![import1](https://user-images.githubusercontent.com/1736110/106226141-80d7c800-6221-11eb-97b8-ae3c9ea59a3c.PNG)

Works, thanks!!! :)

**Comment by Ayasalem01** [comment]
Hello, I am facing the same issue here 2022. Could not find any solution to this.

**Comment by jasontdev** [comment]
@Ayasalem01 installation instructions were updated. Does imported the zip no longer work?

**Comment by mabwh** [comment]
@jasontdev I am using Apache Netbeans 19 on Ubuntu 22.04.3 LTS.
I downloaded the latest ZIP file from  [https://draculatheme.com/netbeans](url)
but after I click on import and choose the ZIP file, no options appear at all.
