### ISSUE TITLE
Doesn't work with Netbeans 12

### ISSUE THREAD

**Issue by ad798** [dracula/netbeans#7]
Hi, today i tried to use it in [Netbeans 12](https://netbeans.apache.org/download/index.html) but nothing happened. How can I make it work? Thanks!!

**Comment by kizinho** [comment]
we are on same boat

**Comment by kizinho** [comment]
find the issue now and have solved it will provide guide

**Comment by jasontdev** [comment]
Just tested with Netbeans 12.4 and theme still imports fine using the zip from the releases: https://github.com/dracula/netbeans/releases/tag/v0.1.0

I will improve the instructions as it is unclear that this zip needs to be downloaded.
