### ISSUE TITLE
Problems with Netbeans 12.0 version

### ISSUE THREAD

**Issue by CommitedBug** [dracula/netbeans#9]
I downloaded the Netbeans 12 LTS, cause it's a LTS version kkkkk. And for my surprise the last release of theme doesn't work on this, but worked in 12.5 version. So I think it's a simple version compatibility issue and it's not too hard to solve, then I ask to the devs to launch a patch.

If anything is written wrong, please excuse me, my English is not good.

**Comment by jasontdev** [comment]
Thankyou for bringing this to my attention, @Angelo-SG. I tried to reproduce this error using a fresh install of Netbeans 12 LTS and the theme appears to be working fine. May I ask how you installed the theme?

**Comment by jasontdev** [comment]
I have updated INSTALL.md with the correct instructions for importing the theme into Netbeans. I am unsure if this is contributing to your issue, but it has been a source of confusion in the past.

**Comment by SNJnet** [comment]
Hi i used netbeans 8, 17 and now 12 and in no version the theme is working. When i import the theme i get a empty options box and after clicking ok nothing happens

**Comment by jasontdev** [comment]
@SNJnet please try importing [dracula-theme-for-netbeans-v0.1.1.zip](https://github.com/dracula/netbeans/files/6574779/dracula-theme-for-netbeans-v0.1.1.zip). I have confirmed it still works in Netbeans 21.
